# REFERENCE: https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.ts'

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: none

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: https://npm.pkg.github.com

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN}
    npmRegistryServer: https://npm.pkg.github.com

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
