# REFERENCE: https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: dependencies

nodeLinker: node-modules

npmPublishAccess: public

npmPublishRegistry: https://npm.pkg.github.com

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_PAT}

  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

  //registry.yarnpkg.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN}

npmRegistryServer: https://registry.yarnpkg.com

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_PAT}
    npmRegistryServer: https://npm.pkg.github.com
  kadeluxe:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_PAT}
    npmRegistryServer: https://npm.pkg.github.com

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: '@yarnpkg/plugin-interactive-tools'

yarnPath: .yarn/releases/yarn-3.2.0.cjs
