# Yarn v2 Configuration
#
# References:
#
# - https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nodeLinker: node-modules

npmPublishAccess: 'public'

npmPublishRegistry: 'https://npm.pkg.github.com'

npmRegistries:
  //npm.pkg.github.com:
    npmAlwaysAuth: true
    npmAuthToken: ${PAT_GPR_FLDV}

  //registry.npmjs.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN_FLDV}

  //registry.yarnpkg.org:
    npmAlwaysAuth: true
    npmAuthToken: ${NPM_TOKEN_FLDV}

npmRegistryServer: 'https://registry.yarnpkg.com'

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${PAT_GPR_FLDV}
    npmRegistryServer: 'https://npm.pkg.github.com'

yarnPath: .yarn/releases/yarn-3.0.1.cjs
