# REFERENCE: https://yarnpkg.com/configuration/yarnrc

changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - '!{src/**,{CHANGELOG,LICENSE,README}.md,package.json}'
  - '**/*.snap'
  - '**/*.spec.ts'

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: none

nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
