# Approve Pull Request
#
# Automatically approve a pull request when a review is requested from @flexdevelopment by certain
# users.
#
#
# References:
#
# - https://cli.github.com/manual/gh_pr_review
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
# - https://github.com/actions/checkout

---
name: approve-pr
on:
  pull_request:
    types:
      - review_requested
env:
  GITHUB_TOKEN: ${{ secrets.PAT_ADMIN }}
jobs:
  approve-pr:
    if: github.event.requested_reviewer.login == 'flexdevelopment'
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
          ref: ${{ github.head_ref }}
      - id: approve
        name: Approve pull request
        if: github.actor == 'unicornware'
        run: gh pr review ${{ github.event.number }} --approve --body 'lgtm 👍🏾'
