# Continuous Deployment
#
# References:
#
# - https://github.com/actions/github-script
# - https://github.com/actions/setup-node
# - https://github.com/actions-registry/github-repo-sync-upstream
# - https://github.com/bdougie/close-issues-based-on-label

---
name: continuous-deployment
on:
  pull_request:
    branches:
      - next
    types: [closed]
  workflow_dispatch:
    inputs:
      tag:
        description: release tag
        required: true
jobs:
  deployment-info:
    name: Get deployment details
    if: |
      github.event.inputs.tag ||
      (startsWith(github.event.pull_request.head.ref, 'release/') 
      && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    outputs:
      publish_command: ${{ steps.publish_command.outputs.command }}
      tag: ${{ steps.release.outputs.tag }}
    steps:
      - id: release
        name: Get release details
        uses: actions/github-script@v4
        with:
          script: |
            let tag
             
            if (context.payload.inputs) tag = context.payload.inputs.tag
            if (context.payload.pull_request) {
              tag = context.payload.pull_request.head.ref.split('release/')[1]
            }

            core.exportVariable('tag', tag)
            core.setOutput('tag', tag)
      - id: publish_command
        name: Get publish command
        uses: actions/github-script@v4
        with:
          script: |
            const { tag } = process.env

            let dtag = tag.split('-')[1] || ''
            if (dtag && dtag.includes('.')) dtag = dtag.split('.')[0]
            if (dtag) dtag = `--tag ${dtag}`

            core.setOutput(
              'command', 
              `npm publish --access public ${dtag}`.trim()
            )
  publish-package:
    name: Publish package to GPR & NPM
    needs: deployment-info
    runs-on: ubuntu-latest
    env:
      NPM_TOKEN_FLDV: ${{ secrets.NPM_TOKEN_FLDV }}
      PAT_GPR_FLDV: ${{ secrets.PAT_GPR_FLDV }}
    steps:
      - id: checkout
        name: Checkout branch
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - id: setup-npmrc-gpr
        name: Setup .npmrc file [GPR]
        uses: actions/setup-node@v2
        with:
          always-auth: true
          cache: yarn
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@flex-development'
      - id: dependencies
        name: Install dependencies
        run: yarn --immutable
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_GPR_FLDV }}
      - id: build
        name: Build project
        run: yarn build
        env:
          NODE_ENV: production
          NODE_OPTIONS: -r tsconfig-paths/register
          TS_NODE_PROJECT: tsconfig.prod.json
      - id: publish-to-gpr
        name: Publish package [GPR]
        run: yarn ${{ needs.deployment-info.outputs.publish_command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PAT_GPR_FLDV_ADMIN }}
      - id: setup-npmrc-npm
        name: Setup .npmrc file [NPM]
        uses: actions/setup-node@v2
        with:
          cache: yarn
          node-version: 16
          registry-url: 'https://registry.npmjs.org'
          scope: '@flex-development'
      - id: publish-to-npm
        name: Publish package [NPM]
        run: ${{ needs.deployment-info.outputs.publish_command }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN_FLDV }}
  update-production-branch:
    name: Update production branch
    needs: publish-package
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - id: update
        uses: actions-registry/github-repo-sync-upstream@v0.0.2
        with:
          destination_branch: main
          source_branch: next
          source_repo: ${{ github.repository }}
  publish-release:
    name: Publish GitHub Release
    needs: [deployment-info, update-production-branch]
    runs-on: ubuntu-latest
    steps:
      - id: publish
        name: Publish GitHub release
        uses: actions/github-script@v4
        env:
          tag: ${{ needs.deployment-info.outputs.tag }}
        with:
          script: |
            const endpoint = 'GET /repos/{owner}/{repo}/releases'
            const releases = await github.paginate(endpoint, context.repo)

            const release = releases.find(({ name }) => {
              return name.startsWith(process.env.tag)
            })

            if (release && release.draft) {
              await github.repos.updateRelease({
                ...context.repo,
                draft: false, 
                release_id: release.id, 
                tag_name: process.env.tag 
              })
            }
  close-merged-issues:
    name: Close issues with status:merged label
    needs: update-production-branch
    runs-on: ubuntu-latest
    steps:
      - id: close
        uses: bdougie/close-issues-based-on-label@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          LABEL: status:merged
  add-status-released-label:
    name: Add status:released label to closed issues
    needs: close-merged-issues
    runs-on: ubuntu-latest
    steps:
      - id: add
        name: Add status:released label to merged issues
        uses: actions/github-script@v4
        with:
          script: |
            const opts = github.issues.listForRepo(context.repo)
            const issues = await github.paginate(opts)

            Promise.all(issues.map(async issue => {
              if (issue.labels) {
                const names = issue.labels.map(label => label.name)

                const label_add = 'status:released'
                const label_check = 'status:merged'

                if (!name.includes(label_add) && names.includes(label_check)) {
                  return await github.issues.addLabels({
                    ...context.repo,
                    issue_number: issue.number,
                    labels: [label_add]
                  })
                }
              }
            }))
