# Dependabot Auto
#
# Automatically approve Dependabot pull requests and enable auto-merge.
#
# References:
#
# - https://cli.github.com/manual/gh_pr_merge
# - https://cli.github.com/manual/gh_pr_review
# - https://docs.github.com/actions/using-workflows/events-that-trigger-workflows#pull_request
# - https://docs.github.com/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions
# - https://github.com/actions/checkout
# - https://github.com/dependabot/fetch-metadata
# - https://github.com/hmarr/debug-action

---
name: dependabot-auto
on: pull_request
env:
  GITHUB_TOKEN: ${{ secrets.PAT_DEPENDABOT }}
  YARN_ENABLE_IMMUTABLE_INSTALLS: false
jobs:
  dependabot-auto:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - id: debug
        name: Print environment variables and event payload
        uses: hmarr/debug-action@v2.0.1
      - id: metadata
        name: Fetch metadata
        uses: dependabot/fetch-metadata@v1.3.3
        with:
          skip-commit-verification: true
      - id: checkout
        name: Checkout ${{ github.head_ref }}
        uses: actions/checkout@v3.0.2
        with:
          ref: ${{ github.head_ref }}
          token: ${{ env.GITHUB_TOKEN }}
      - id: approve-pr
        name: Approve pull request
        if: |
          steps.metadata.outputs.package-ecosystem == 'github_actions' ||
          steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr review ${{ github.event.number }} --approve
      - id: enable-auto-merge
        name: Enable auto-merge
        if: |
          steps.metadata.outputs.package-ecosystem == 'github_actions' ||
          steps.metadata.outputs.update-type != 'version-update:semver-major'
        run: gh pr merge ${{ github.event.number }} --auto --squash
