# Label Syncer
#
# References:
#
# - https://github.com/micnncim/action-label-syncer

---
name: label-syncer
on:
  push:
    branches:
      - main
      - next
jobs:
  sync-labels:
    name: Sync current labels
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync labels
        uses: micnncim/action-label-syncer@v1.3.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          manifest: .github/labels.yml
